FROM php:7.4-apache

# PHP extensions
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql \ 
    && apt-get clean && rm -rf /var/lib/apt/lists/* \
    